db:
  image: mariadb
  volumes:
    - ./mysql/runtime:/var/lib/mysql
  env_file:
    - ./.env
web:
  image: auburndaleoxwall
  links:
    - db
  volumes:
    - ./data:/var/www/html
  env_file:
    - ./.env
cron:
  image: auburndaleoxwall
  command: cron -f
  volumes:
    - ./crontab:/etc/cron.d/oxwall
  volumes_from:
    - web
  links:
    - db
